# Generated by Django 3.1.3 on 2021-03-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ACL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('networks', models.TextField()),
                ('services', models.TextField()),
                ('terms', models.TextField()),
                ('static_definitions_dir', models.TextField()),
                ('policy_template_path', models.TextField()),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
