# Generated by Django 3.1.3 on 2021-04-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_capirca_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acl',
            name='policy_template_path',
            field=models.TextField(default='/opt/capirca/policies/main.pol.j2'),
        ),
        migrations.AlterField(
            model_name='acl',
            name='static_definitions_dir',
            field=models.TextField(default='/opt/capirca/defs/'),
        ),
    ]
