# Generated by Django 3.1.3 on 2021-04-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_capirca_plugin', '0002_auto_20210401_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acl',
            name='policy_template_path',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='acl',
            name='static_definitions_dir',
            field=models.TextField(),
        ),
    ]
