# Generated by Django 3.1.3 on 2021-04-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_capirca_plugin', '0003_auto_20210401_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='acl',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acl',
            name='networks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='acl',
            name='services',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='acl',
            name='terms',
            field=models.TextField(blank=True),
        ),
    ]
