# Generated by Django 3.1.3 on 2021-04-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_capirca_plugin', '0005_auto_20210401_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acl',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
