# Generated by Django 3.1.3 on 2021-04-03 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_capirca_plugin', '0007_aclinterfaceassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aclinterfaceassignment',
            name='acl',
        ),
        migrations.RemoveField(
            model_name='aclinterfaceassignment',
            name='direction',
        ),
        migrations.AddField(
            model_name='aclinterfaceassignment',
            name='egress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aclinterfaceassignment_egress', to='netbox_capirca_plugin.acl'),
        ),
        migrations.AddField(
            model_name='aclinterfaceassignment',
            name='ingress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aclinterfaceassignment_ingress', to='netbox_capirca_plugin.acl'),
        ),
    ]
