# Generated by Django 3.1.3 on 2021-04-04 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0122_standardize_name_length'),
        ('netbox_capirca_plugin', '0008_auto_20210403_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aclinterfaceassignment',
            name='interface',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dcim.interface'),
        ),
    ]
