# Generated by Django 3.1.3 on 2021-04-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_capirca_plugin', '0009_auto_20210404_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acl',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
